### ISSUE TITLE
`isRepoRoot` matches all of the `isUserProfile` tabs

### ISSUE THREAD

**Issue by yakov116** [fregante/github-url-detection#19]
Example: https://github.com/sindresorhus?tab=repositories&type=source

I think the following needs `isRepo`
https://github.com/fregante/github-url-detection/blob/4ff46aa7f89141e45c09bc9957fda4dfa4787b54/index.ts#L297

// cc @FloEdelmann

**Comment by fregante** [comment]
Specifically, it needs the /tree/ part on the URL, so the logic needs to be sorted out
