### ISSUE TITLE
Fix auto-deployment

### ISSUE THREAD

**Issue by fregante** [fregante/github-url-detection#22]
It's unclear what the problem is, but `npm publish` throws for some reason. Help wanted to debug this.

```
npm notice 📦  github-url-detection@1.2.1
npm notice === Tarball Contents === 
npm notice 1.1kB  license         
npm notice 11.8kB cjs/index.js    
npm notice 11.5kB esm/index.js    
npm notice 22B    esm/package.json
npm notice 1.7kB  package.json    
npm notice 2.8kB  readme.md       
npm notice 5.2kB  cjs/index.d.ts  
npm notice 5.2kB  esm/index.d.ts  
npm notice === Tarball Details === 
npm notice name:          github-url-detection                    
npm notice version:       1.2.1                                   
npm notice package size:  7.1 kB                                  
npm notice unpacked size: 39.4 kB                                 
npm notice shasum:        6f51c2edac9a387c670b71c28f0144026fa708b9
npm notice integrity:     sha512-KB+69+slQ+NTG[...]BjP0a3QJ2oEXA==
npm notice total files:   8                                       
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/github-url-detection - Not found
npm ERR! 404 
npm ERR! 404  'github-url-detection@1.2.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

https://github.com/fregante/github-url-detection/actions/runs/137623208/workflow

**Comment by Nic30** [comment]
Suffering from same issue [d3-wave](https://github.com/Nic30/d3-wave.git) https://travis-ci.org/github/Nic30/d3-wave/builds/708811795

@fregante did you found out what is causing the issue?

**Comment by fregante** [comment]
No idea. Let me know if you do

**Comment by Nic30** [comment]
It seems that after nearly 2 years my api key just stopped working. I checked and based on last digits I used the correct one.
However it was not working. I generated and used a new api key and it is now working.
https://travis-ci.org/github/Nic30/d3-wave/builds/708819721
I used `travis encrypt <api key> --add deploy.api_key` to update key for travis as described in https://docs.travis-ci.com/user/deployment/npm/

**Comment by fregante** [comment]
The issue seems to appear when the token is missing or incorrect. I don't know why it wouldn't work before, but I generated it once again and it finally worked.

**Comment by fregante** [comment]
I following the instructions by using a secondary account, but now I got another error:

```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/github-url-detection - You do not have permission to publish "github-url-detection". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```

... which is ridiculous. The UI says that the user has write access.

I ended up disabling 2FA for the package and for my user (every package has its own 2FA setting anyway, so my other packages aren't affected)

Now it works, finally: https://github.com/fregante/github-url-detection/runs/907917732?check_suite_focus=true

Next problem: https://github.com/fregante/github-url-detection/issues/27
