### ISSUE TITLE
`isRepoRoot` Fails on https://github.com/Witold101/wpw

### ISSUE THREAD

**Issue by yakov116** [fregante/github-url-detection#24]
https://github.com/Witold101/wpw

I can't figure out why. Maybe because the username start with an upper case letter? but in this repo we are not doing `.toLowercase()`??

**Comment by notlmn** [comment]
Both repo and usernames are case-insensitive as far as GitHub is considered.

`getRepoURL()` and similar getters should no convert to other cases while returning, instead that should be left to functions like `isRepoRoot()`.

Example:

``` js
function isRepoRoot() {
	// ...
	return document.title.toLowerCase().startsWith(getRepoURL().toLowerCase()) && ...
}
```

**Comment by notlmn** [comment]
Looks like `link[rel="alternative"]` can betray you sometimes too. There is stuff like `meta[name="go-import"]` and other analytics tags.

![image](https://user-images.githubusercontent.com/37769974/87315275-ed1f0280-c541-11ea-9981-f406b3b32ad0.png)

**Comment by yakov116** [comment]
select.last

**Comment by yakov116** [comment]
Figured it out.
https://github.com/fregante/github-url-detection/blob/91f020d54264ecd443e80e6d2cc4e6c1943725f6/index.ts#L298

On is repoRoot we want to make sure we are not on the home so we detect is the title matches (so I think). However if the repo does not have a description the the title will match.

Example:
This repo: "fregante/github-url-detection: Which GitHub page are you on? Is it an issue? Is it a list? Perfect for your WebExtension or userscript."
Witold101/wpw: "Witold101/wpw"

Not sure how to go about it

**Comment by fregante** [comment]
How does my PR look?

**Comment by yakov116** [comment]
@fregante your pr's always look good 😁

I am away from the computer for the next while I will test it and let you know.

**Comment by fregante** [comment]
@notlmn we can use `rel=canonical` inside `getRepoURL` IF `url` isn't specified, but that doesn't appear on every page.

`og:url` seems to appear on every page: https://github.com/fregante/github-url-detection/pull/26
