### ISSUE TITLE
Create release notes via GitHub Actions

### ISSUE THREAD

**Issue by fregante** [fregante/github-url-detection#27]
Tags created via GA don't currently have an associated release. Help wanted to find an easy-to-use action to create it.

https://github.com/fregante/github-url-detection/releases

**Comment by notlmn** [comment]
> Help wanted to find an easy-to-use action to create it.

Let's build one!

**Comment by fregante** [comment]
😱

**Comment by fregante** [comment]
Indeed this would also help Refined GitHub and any other auto-deployed extension
