### ISSUE TITLE
Rename `isActions`

### ISSUE THREAD

**Issue by yakov116** [fregante/github-url-detection#41]
There are 2 kind of actions.

1. Marketplace actions
2. Repo Actions

`isMarketplaceActions`?

I think that `isActions` should be the repo one and have `isMarketplaceActions` as an addition

WDYT?

The current actions
https://github.com/fregante/github-url-detection/blob/0f8a4260f3f869c537b2e9f878ff2f712c4a363d/index.ts#L448-L453

**Comment by fregante** [comment]
Totally. This should be named `isMarketplaceAction` (not `s`, it's just one)

You can deprecate `isActions` and add `isRepositoryActions`
