### ISSUE TITLE
Detecting the two kinds of GitHub Security advisories

### ISSUE THREAD

**Issue by JLLeitschuh** [fregante/github-url-detection#52]
GitHub has two different kinds of advisories.

The first is the advisories that are published by the repository owners themselves. The last URL part will always end with 'GHSA'. Here's an example of the URL for these:

 - https://github.com/eclipse/jetty.project/security/advisories/GHSA-g3wg-6mcf-8jj6

The second is the advisory that is curated by GitHub, these are similar, but not the same as the advisories published by the project maintainers. These versions are curated/modified/updated by GitHub staff themselves. These get generated after an advisory is published and processed by GitHub. Here's an example of the URL for that:

 - https://github.com/advisories/GHSA-g3wg-6mcf-8jj6

Also, the above URL incorrectly reports that that URL is:

```
isRepo(url) // true
isRepoHome(url) // true
isRepoRoot(url) // true
isRepoTree(url) // true
```

**Comment by fregante** [comment]
Thanks for the report!

The first URL is reported correctly:

<img width="810" alt="Screen Shot 2020-11-20 at 11 15 20" src="https://user-images.githubusercontent.com/1402241/99829268-b4132200-2b21-11eb-9475-a3112e8c1158.png">

I'll fix the second one in https://github.com/Mottie/github-reserved-names

**Comment by fregante** [comment]
Are you requesting to add a detection specifically for advisories? If so, PR welcome for `isAdvisory` and `isRepoAdvisory` (or more generally `isRepoSecurity`)

**Comment by JLLeitschuh** [comment]
> I'll fix the second one in https://github.com/Mottie/github-reserved-names

Awesome!

> If so, PR welcome for `isAdvisory` and `isRepoAdvisory` (or more generally `isRepoSecurity`)

I was thinking about adding a mod to [refined github](https://github.com/sindresorhus/refined-github) that mods the advisories page. Updating this repo would be a prerequisite. I'll try to get around to this soon.

**Comment by fregante** [comment]
> I was thinking about adding a mod to [refined github](https://github.com/sindresorhus/refined-github) that mods the advisories page

Request that first so we know whether/what is needed here.

> I'll fix the second one in [Mottie/github-reserved-names](https://github.com/Mottie/github-reserved-names)

Added: https://github.com/Mottie/github-reserved-names/commit/970c9816b244781a27550779e548499fac8d7fb7

Now we wait for the next release

**Comment by yakov116** [comment]
> Now we wait for the next release

It was already
https://github.com/Mottie/github-reserved-names/releases

**Comment by fregante** [comment]
Ugh that’s the problem with package locks, they must be updated manually 😅 let me push a new release

**Comment by yakov116** [comment]
> Ugh that’s **one of the many** problem **I have** with package locks, they must be updated manually 😅 let me push a new release

**Comment by fregante** [comment]
Closing this. They’ll come when needed.
