### ISSUE TITLE
Demo website is broken

### ISSUE THREAD

**Issue by cheap-glitch** [fregante/github-url-detection#57]
It seems like the demo website is broken (tested in latest Firefox and Chromium). The page is blank except for the explanation message and the following console error is produced:
```
Uncaught TypeError: e.default is not a constructor
    epB2 https://fregante.github.io/github-url-detection/main.127a4158.js:4
    f https://fregante.github.io/github-url-detection/main.127a4158.js:1
    parcelRequire https://fregante.github.io/github-url-detection/main.127a4158.js:1
    <anonymous> https://fregante.github.io/github-url-detection/main.127a4158.js:1
main.127a4158.js:4:182
```

**Comment by fregante** [comment]
Thanks for the report, it had been broken since https://github.com/fregante/github-url-detection/commit/12e096105fd0470569bc46adb530086e185d47d4
