### ISSUE TITLE
Update isOpenPR and related detections

### ISSUE THREAD

**Issue by fregante** [fregante/github-url-detection#67]
From
```js
exists('#partial-discussion-header [title="Status: Open"], #partial-discussion-header [title="Status: Draft"]')
```

to

```js
exists('.gh-header-meta [title$="Open"], .gh-header-meta [title$="Draft"]'),
```

but more likely a mix of the 2.

Note: let's not use `:is` yet, it'd be a breaking change.

**Comment by yakov116** [comment]
Curios why?

**Comment by fregante** [comment]
You mean about `:is`? Using it increases the previous minimum browser support.

**Comment by yakov116** [comment]
No ⬇️ 

> From
> 
> ```js
> exists('#partial-discussion-header [title="Status: Open"], #partial-discussion-header [title="Status: Draft"]')
> ```
> 
> to
> 
> ```js
> exists('.gh-header-meta [title$="Open"], .gh-header-meta [title$="Draft"]'),
> ```

**Comment by fregante** [comment]
I assumed that RG’s selector is more up to date and that this one was outdated. I guess not.
