### ISSUE TITLE
Missing detection for creating new files

### ISSUE THREAD

**Issue by darkred** [fregante/github-url-detection#68]
*Per https://github.com/sindresorhus/refined-github/pull/4252#discussion_r615968923*

In the PR above I want to match patterns of both these URL examples:
```
- Create new file:         https://github.com/sindresorhus/refined-github/new/main
- Modify an existing file: https://github.com/sindresorhus/refined-github/edit/main/readme.md
```

Checking them via https://fregante.github.io/github-url-detection/ I see that :
![2021-04-19_184538](https://user-images.githubusercontent.com/723651/115267567-fe84e300-a141-11eb-815f-9586c893bab3.jpg)
![2021-04-19_190318](https://user-images.githubusercontent.com/723651/115267542-f62ca800-a141-11eb-9c79-894c1a1656b2.jpg)

So I have in the PR the following:

```
	include: [
		...
		pageDetect.isRepo,
		pageDetect.isEditingFile
	],
```

**But**, as mentioned by @yakov116:

> Adding `isRepo` will add it to all repo pages (PR's Issues etc)

**Comment by yakov116** [comment]
Maybe it should be a new option `isCreatingNewFile` ?

**Comment by fregante** [comment]
isNewFile 👍

**Comment by darkred** [comment]
I made PR #70
