### ISSUE TITLE
Discussions aren't part of `hasComments`

### ISSUE THREAD

**Issue by fregante** [fregante/github-url-detection#78]
Was this a conscious choice or should we add it?

Example https://github.com/aminomancer/uc.css.js/discussions/4

<img width="577" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/117820962-4a383180-b295-11eb-8958-ab881c24f964.png">

**Comment by yakov116** [comment]
Yes because we run special things on it that do not apply to discussions. The dom is entirely different.

**Comment by yakov116** [comment]
See https://github.com/fregante/github-url-detection/pull/59

**Comment by fregante** [comment]
Indeed, let's just enable `fit-textareas` on discussions then. Closing this and reopening the other issue

**Comment by fregante** [comment]
How about hasRichTextEditor? 🤔 I think it should be part of that
