### ISSUE TITLE
Organization sub tabs are not detected

### ISSUE THREAD

**Issue by yakov116** [fregante/github-url-detection#84]
Example URL https://github.com/orgs/tc39/packages

I would think it would be included in `isOrganizationProfile()` just like is `isUserProfile`

I think just checking for /orgs should be enough

**Comment by fregante** [comment]
Detected for what? In which function?

**Comment by yakov116** [comment]
Hiding packages etc

**Comment by fregante** [comment]
If you say they're "not detected" I think that you're expecting that an existing function/detection is miscategorizing this page. I'm asking: Which function is this?

If there's no such function yet, it's not that they're "not detected", you're just asking for a new function.

**Comment by yakov116** [comment]
I don't need this anymore
