### ISSUE TITLE
bug: is404 incorrect when not logged in

### ISSUE THREAD

**Issue by privatenumber** [fregante/github-url-detection#98]
This code doesn't seem to work when not logged in because the title is `Page not found · GitHub · GitHub`:
https://github.com/fregante/github-url-detection/blob/ca4edcfdc87e26241c10fb27985d73af8d024630/index.ts#L14

#### Logged in
<img width="551" alt="Screen Shot 2021-10-16 at 3 23 36 PM" src="https://user-images.githubusercontent.com/1075694/137599773-8601f428-0c15-44bf-98b7-45210805423c.png">

#### Not logged in
<img width="592" alt="Screen Shot 2021-10-16 at 3 25 14 PM" src="https://user-images.githubusercontent.com/1075694/137599817-96f9a393-394c-405a-9a68-0eb17dbf0c57.png">

**Comment by fregante** [comment]
Generally these detections are supposed to work when logged out, but this looks like an easy change. PR welcome to change the detection from === to .startsWith
